### ISSUE TITLE
v4 ENHANCEMENT - Config Parsing

### ISSUE THREAD

**Issue by Jake-Moore** [Jake-Moore/KamiCommon#136]
## FEATURE - Config Parsing
- [ ] Double check that all YAML types are properly supported, and we aren't turning everything into a string
- [ ] Need support for object lists (`ConfigurationSectionList` or something), which has ways of obtaining a new subclass that has standard key fetching methods like .getString("id")
```yaml
weapons:
  - id: "sword"
    damage: 10
    durability: 100
  - id: "bow"
    damage: 8
    durability: 50
```
Maybe investigate the `jackson-dataformat-yaml` library (which brings SnakeYaml with it) for mapping Yaml to Java objects automatically. Since this is a post v4 release plan, we need to write an api ontop of the existing v4 without breaking the api.
